### ISSUE TITLE
Check Authorize trước khi lấy role của user

### ISSUE THREAD

**Issue by hoangvu0905** [ThanhDeveloper/AspNetCoreWebApplicationTemplate#2]
Nên đẩy code check no authorize lên trước code lấy role user 
https://github.com/ThanhDeveloper/WebApplicationAspNetCoreTemplate/blob/master/AspNetCoreTemplate/Common/Attributes/CustomAuthorizeAttribute.cs#L23 chuyển lên trước L19

**Comment by ThanhDeveloper** [comment]
Cảm ơn bạn. Mình sẽ điều chỉnh lại ^^
